name: Leer progreso

on:
  workflow_dispatch:

jobs:
  read:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_USER: gabrielrpalavecino-dotcom
      GITHUB_REPO: relajacion

    steps:
      - uses: actions/checkout@v3

      - name: Mostrar progreso
        run: |
          cat data/progreso.json
